# Generated by Django 2.2.7 on 2021-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_qlength_rules_visitor_words_wordtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='word_type',
        ),
        migrations.AlterField(
            model_name='wordtype',
            name='after',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wordtype',
            name='before',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
