# Generated by Django 2.2.7 on 2021-12-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20211130_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QLength',
        ),
        migrations.AlterField(
            model_name='wordtype',
            name='after',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wordtype',
            name='before',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
