# Generated by Django 2.2.7 on 2021-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_visitor_end_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtype',
            name='before',
        ),
    ]
